version: '3.5'

services:
  hexo:
    container_name: hexo
    build:
       context: .
       dockerfile: ./docker/Dockerfile
    ports: 
      - "4000:4000"
    volumes:    # 主机路径:docker内部路径
      - .:/app
    entrypoint: sleep 3600      # 用于调试
    # entrypoint: hexo server
    tty: true
