version: '3.5'

services:
  hexo:
    container_name: hexo
    build:
       context: .
       dockerfile: ./Dockerfile
    ports: 
      - "4000:4000"
    volumes:    # 主机路径:docker内部路径
      - ./source/_posts.my:/app/source/_posts
    # entrypoint: sleep 3600      # 用于调试
    entrypoint: hexo server
    tty: true
